-- Lists all genres from hbtn_0d_tvshows and displays the number of shows linked to each
-- Record display: <TV show genre> - <number of shows linked to genre>
-- Sorted in ascending order by number of shows linked
